language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
jobs:
  include:
    - stage: tdd
      script:
      - yarn build
      - yarn test:unit

    - stage: e2e
      before_script:
        - yarn install
      script:
      - yarn run serve &
      - yarn snapshots
